version: '3'

services:

  postgres:
    image: 'postgres:14.5'
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: movies
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - '5431:5432'
    volumes:
      - ./go-movies-back-end/postgres-data:/var/lib/postgresql/data
      - ./go-movies-back-end/sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
